/**
 * SponsorPay Android SDK
 *
 * Copyright 2011 - 2014 SponsorPay. All rights reserved.
 */

package com.sponsorpay.utils;

import java.util.UUID;

import android.content.Context;
import android.content.SharedPreferences;
import android.content.SharedPreferences.Editor;

import com.sponsorpay.publisher.SponsorPayPublisher;

public class UserId {
	
	public static final String STATE_GENERATED_USERID_KEY = "STATE_GENERATED_USERID_KEY";

	public static synchronized String getAutoGenerated(Context context) {
		SharedPreferences state = context.getSharedPreferences(
				SponsorPayPublisher.PREFERENCES_FILENAME, Context.MODE_PRIVATE);

		String userIdValue = state.getString(STATE_GENERATED_USERID_KEY, null);

		if (userIdValue == null) {

			userIdValue = generateUserId();

			Editor stateEditor = state.edit();
			stateEditor.putString(STATE_GENERATED_USERID_KEY, userIdValue);
			stateEditor.commit();
		}
				
		return userIdValue;
	}

	private static String generateUserId() {
		StringBuilder builder = new StringBuilder();
		
		builder.append(UUID.randomUUID());

		String baseText = builder.toString();
		String generatedId = SignatureTools.generateSHA1ForString(baseText);

		if (generatedId == null || generatedId.equals(SignatureTools.NO_SHA1_RESULT)) {
			generatedId = baseText;
		}

		return generatedId;
	}
}
